### ISSUE TITLE
Smooth Scroll action is being updated too frequently. Make sure you are not changing it unless necessary

### ISSUE THREAD

**Issue by rafiwew** [Ahmad-Hamwi/TabSync#8]
Smooth Scroll action is being updated too frequently. Make sure you are not changing it unless necessary.

How to fix this message error?

<img width="1440" alt="Jepretan Layar 2023-12-17 pukul 01 01 09" src="https://github.com/Ahmad-Hamwi/TabSync/assets/61513614/0dcba991-090a-4a65-bf35-35de3e62e161">

**Comment by rafiwew** [comment]
<img width="1440" alt="Jepretan Layar 2023-12-17 pukul 01 01 09" src="https://github.com/Ahmad-Hamwi/TabSync/assets/61513614/9db9a4fd-3333-47cc-b695-98aabfa0ab73">

**Comment by Ahmad-Hamwi** [comment]
Thank you for opening the issue.

I'm not sure what's causing the problem exactly, as I couldn't reproduce it.

Some folks online say that it seems that it's related to the SmoothScroller that is being used, and it should be used only once for each trigger of a smooth scroll. And indeed, the logcat is printing warning messaging regarding this, so I will add this change to the next release.

But for further investigation, kindly provide me with a minimal working project that produces these error messages.
